# Generated by Django 4.0.4 on 2022-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('country_code', 'phone_number')},
        ),
    ]
