# Generated by Django 4.0.4 on 2022-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager_app', '0002_alter_recipient_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
