# Generated by Django 4.0.4 on 2022-04-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager_app', '0006_alter_mailing_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
