# Generated by Django 4.0.4 on 2022-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager_app', '0007_alter_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
