# Generated by Django 4.0.4 on 2022-04-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager_app', '0008_mailing_finalized'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('mailing', 'recipient')},
        ),
    ]
